### ISSUE TITLE
git clone 허가 거부

### ISSUE THREAD

**Issue by lspc678** [Eye-Remocon/git-study#1]
혹시 edge-home-orchestration-go 폴더를 clone 하신분 있나요? 허가거부가 떠서 clone이 안되네요.
![git clone 허가거부](https://user-images.githubusercontent.com/79794123/115979566-9c086880-a5c1-11eb-8936-c7a75ff67e18.png)

**Comment by lspc678** [comment]
아 앞에 sudo 붙이니까 되네요.
![git clone 해결](https://user-images.githubusercontent.com/79794123/115979643-0c16ee80-a5c2-11eb-90b2-8edb20bfe9d8.jpg)

**Comment by t25kim** [comment]
@lspc678 sudo 는 관리자 권한이라 가급적이면 활용하지 않는게 좋아요. 
폴더 권한이 어떻게 되어있나 한 번 보시고 chmod 나 chown 으로 변경해보시는게 좋을 것 같아요.

**Comment by smarthome-hanium** [comment]
@lspc678 sudo 는 관리자 권한이라 가급적이면 활용하지 않는게 좋아요.
폴더 권한이 어떻게 되어있나 한 번 보시고 chmod 나 chown 으로 변경해보시는게 좋을 것 같아요.

**Comment by lspc678** [comment]
감사합니다.
