### ISSUE TITLE
명령어를 찾을 수 없음

### ISSUE THREAD

**Issue by lspc678** [Eye-Remocon/git-study#2]
@Seunghui98 @woniiiii @Ryumaker 

./build.sh 명령어를 사용했는데 명령어를 찾을 수 없다고 나오네요. 혹시 해결하신분 있나요?

![명령어를 찾을 수 없음](https://user-images.githubusercontent.com/79794123/116518138-d9932b80-a90a-11eb-91a6-d6676964facb.jpg)

**Comment by smarthome-hanium** [comment]
아래처럼 apt-get을 활용해서 make 툴을 설치하시면 될 것 같아요. 
`$ sudo apt-get install build-essential`

**Comment by lspc678** [comment]
감사합니다. 해결되었습니다.
