### ISSUE TITLE
Eye-Remocon/MeetingNote Upstream Fetch 충돌 문제

### ISSUE THREAD

**Issue by Seunghui98** [Eye-Remocon/git-study#3]
Eye-Remocon/MeetingNote를 Fork 하여서 Upstream Fetch 하고 싶은데
자꾸 충돌이 뜨는데 해결하신 분 계신가요?
지난번에 제가 Meeting Note 중 0404.md에 관해서 PR 올렸는데 
Conflict 떠서 해결했는데도 그 부분이 계속 충돌이라고 Upstream Fetch가 안되는 것 같습니다.
혹시 해결법 아시는 분 있으시다면 Comment 부탁드려요 ! 

@lspc678 @smarthome-hanium @woniiiii @Ryumaker

**Comment by lspc678** [comment]
아마 같은 부분을 수정하여 생긴 것 같습니다. 해결되면 다시 comment 올려드릴게요.

**Comment by lspc678** [comment]
혹시 fork 하신 다음에 branch 생성하셨나요. branch 생성은 터미널에서

git branch <생성할 branch 이름>

이렇게 작성하시면 됩니다.

**Comment by lspc678** [comment]
@Seunghui98 혹시 fork 하신 다음에 branch 생성하셨나요. branch 생성은 터미널에서

git branch <생성할 branch 이름>

이렇게 작성하시면 됩니다.
